const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ActivitiesSchema = new Schema({
  Country: String,
  PartofCountry: String,
  City: String,
  Cityofaccommodation: String,
  FeaturedImage: String,
  EventCode: Number,
  Headingofevent: String,
  PlacesCovered: String,
  SICPriceUSD: Number,
  SICPrice: Number,
  Breakfast: String,
  Lunch: String,
  Dinner: String,
  InclusionName: String,
  ShortDescription: String,
  LongDescription: String,
  Durationofevent: String,
  TimeSlot: String,
  TransferInclusion: String,
  GroupType: String,
  PricePerPax: Number,
  price2Pax$: Number,
  price2PaxRs: Number,
  price3Pax$: Number,
  price3PaxRs: Number,
  price4Pax$: Number,
  price4PaxRs: Number,
  PriceinRupees: Number,
  PriceType: String,
  MealDuringEvent: String,
  AccommodationForTheNight: String,
  StartTimeOfEvent: String,
  EndtimeOfEvent: String,
  Transfers: String,
  OtherFilters: String,
  Highlightsoftheevent: String,
  Spotscovered: String,
  AddedInclusions: String,
  Conditions: String,
  ConnectingFlights: String,
  Tags: String
});

module.exports = mongoose.model('Activities', ActivitiesSchema);
